language: python

python:
    - 3.6
    - 3.7

env:
    - CTAPIPE_VERSION="v0.7.0" CTAPIPE_IO_LST_VERSION="v0.4.1" PROTOZFITS_VERSION=v1.4.2
    - CTAPIPE_VERSION="master" CTAPIPE_IO_LST_VERSION="master" PROTOZFITS_VERSION="master"

matrix:
  allow_failures:
      - env: CTAPIPE_VERSION="master" CTAPIPE_IO_LST_VERSION="master" PROTOZFITS_VERSION="master"

  include:
      - env: CTAPIPE_VERSION="v0.7.0" CTAPIPE_IO_LST_VERSION="v0.2" PROTOZFITS_VERSION=v1.4.2


before_install:

    # Use utf8 encoding. Should be default, but this is insurance
    # against future changes
    - export PYTHONIOENCODING=UTF8
    - export MPLBACKEND=Agg

    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - . $HOME/miniconda/etc/profile.d/conda.sh
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda  # get latest conda version
    - conda info -a # Useful for debugging any issues with conda

install:
    - conda env create --file environment.yml
    - conda activate lst-dev
    - pip install https://github.com/cta-observatory/ctapipe/archive/$CTAPIPE_VERSION.tar.gz
    - pip install https://github.com/cta-observatory/ctapipe_io_lst/archive/$CTAPIPE_IO_LST_VERSION.tar.gz
    - python setup.py install


script:
    - pytest lstchain

