---
language: python

env:
  global:
    - PYTHONIOENCODING=UTF8
    - MPLBACKEND=Agg
    - PYTEST_ADDOPTS='--color=yes'


matrix:
  include:
    - name: "python=3.6, ctapipe=0.8"
      python: 3.6
      env:
        - CTAPIPE_VERSION="v0.8.0"
        - CTAPIPE_IO_LST_VERSION="v0.5.3"

    - name: "python=3.7, ctapipe=0.8"
      python: 3.7
      env:
        - CTAPIPE_VERSION="v0.8.0"
        - CTAPIPE_IO_LST_VERSION="v0.5.3"

    - name: "python=3.6, ctapipe=master"
      python: 3.6
      env:
        - CTAPIPE_VERSION="master"
        - CTAPIPE_IO_LST_VERSION="master"

    - name: "python=3.7, ctapipe=master"
      python: 3.7
      env:
        - CTAPIPE_VERSION="master"
        - CTAPIPE_IO_LST_VERSION="master"

  allow_failures:
    - name: "python=3.6, ctapipe=master"
    - name: "python=3.7, ctapipe=master"


before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - . $HOME/miniconda/etc/profile.d/conda.sh
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda  # get latest conda version
    - conda info -a  # Useful for debugging any issues with conda

install:
    - sed -i -e "s/- python=.*/- python=$TRAVIS_PYTHON_VERSION/g" environment.yml
    - conda env create --file environment.yml
    - conda activate lst-dev
    - python --version
    - |
      pip install \
      https://github.com/cta-observatory/ctapipe/archive/$CTAPIPE_VERSION.tar.gz \
      https://github.com/cta-observatory/ctapipe_io_lst/archive/$CTAPIPE_IO_LST_VERSION.tar.gz \
      pytest-cov codecov
    - pip install .


script:
    - pytest --cov lstchain --cov-report=xml lstchain

after_success:
    - codecov

deploy:
    provider: pypi
    user: "__token__"
    password:
        secure: "UHZE1CjUCAkkYB8UTFYuXZ3d+bY7Ney5myLJGbSFGMnCGOix8sCO4bkvN9JMMeCHQX1C+nIe/pck8e2C5240juRp/H88vABxhkA0l05X7o+9jGmaVNITxPoFrdwoQ2GSk9DnCEmOn4/CBMXU9maFdQ3NC7uImD/d9NgdGweSdZWJVrV9ZuCZ3E1FOONgTeAIl2wT6R2G95LIRuf1EZfvBdXCmQNbm/06ZiJy7BjMqJPpH7rJD06bxm7vPPTcMvvEh6CUh2IxmNFA7Lh6KjrYH7YhwKqWqoBEkIeiTqpMyBTNKvLbsu9jlh9WDhtIGSX1Wup0Fd/WLfX8xqEq84XSqERiKK8cuNhkztHanWza0sz+kZLPZjqLkERpkzXZCNO0d4eNkcVzSYMdu1YgjosAKB/+mqSCKpOwGMTca+rKLhcWAQCLZrI+txlIKgabcoCpRcs7qB0DUXlRJ80Dg5bt3thgZ2j11yTF14dOOk/EhJdvPM4qFCN2x/lQkwkj6549qOuQKD2gSlqFM8F3W0vKc88ys+hPVe7sszLbxv+h7XyEFYqo6/6ItCxZ0+t1jyv8d59425yCz9U5n7X8N83LBomkO7VvCo2G4YFI4r+lyEJ7VjwGcUacC1w6Bs8oCTT8QYQeFR7YxIL2w+CEd5NMInJMfpiDbpuwSTUTb3UVNpA="
    distributions: sdist
    skip_existing: true
    skip_cleanup: true
    on:
        tags: true
        branch: master
        condition: $TRAVIS_PYTHON_VERSION = "3.7"
