[build-system]
requires = ["setuptools >= 40.6.0", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = [
	"private_data"
]
filterwarnings = [
     "ignore::ctapipe.core.provenance.MissingReferenceMetadata",
]
